# 1. Assume a Poisson distribution
a) If lambda = 2.5, Find P(X = 2)

b) If lambda = 0.5, Find P(X = 1)

a) 0.2565
b) 0.3033

In [1]:
import numpy as np 
import scipy.stats as stats
import matplotlib.pyplot as plt

In [2]:
rate=2.5

In [3]:
n=np.arange(0,20)

In [5]:
poisson_a=stats.poisson.pmf(n,rate)
poisson_a

array([8.20849986e-02, 2.05212497e-01, 2.56515621e-01, 2.13763017e-01,
       1.33601886e-01, 6.68009429e-02, 2.78337262e-02, 9.94061650e-03,
       3.10644266e-03, 8.62900738e-04, 2.15725184e-04, 4.90284510e-05,
       1.02142606e-05, 1.96428089e-06, 3.50764445e-07, 5.84607408e-08,
       9.13449075e-09, 1.34330746e-09, 1.86570481e-10, 2.45487475e-11])

In [6]:
poisson_a[2]

0.25651562069968376

In [7]:
rate=0.5

In [8]:
n=np.arange(0,10)

In [9]:
poisson_b=stats.poisson.pmf(n,rate)
poisson_b

array([6.06530660e-01, 3.03265330e-01, 7.58163325e-02, 1.26360554e-02,
       1.57950693e-03, 1.57950693e-04, 1.31625577e-05, 9.40182694e-07,
       5.87614184e-08, 3.26452324e-09])

In [10]:
poisson_b[1]

0.3032653298563167

# 2. Assume a poisson distribution with lambda = 5.0. What is the probability that
a) X <= 1?

b) X > 1?

a) 0.0404
b) 0.9596

In [11]:
rate =5

In [12]:
n=np.arange(0,10)

In [13]:
poisson_a=stats.poisson.pmf(n,rate)
poisson_a

array([0.00673795, 0.03368973, 0.08422434, 0.1403739 , 0.17546737,
       0.17546737, 0.14622281, 0.10444486, 0.06527804, 0.03626558])

In [17]:
prob=poisson_a[0]+poisson_a[1]
prob

0.040427681994512805

In [18]:
#probability for X>1 is equal to 1- prob
prob_b=1-0.040427681994512805
prob_b



0.9595723180054871

# 3. The number of work related injuries per month in a manufacturing plant is known to follow a Poisson distribution, with a mean of 2.5 work-related injuries a month.

a) What is the probability that in a given month, no work-related injuries occur?

b) That at least one work- related injury occurs?

Hint: Use Poisson distribution equation, find X = 0, Given lambda = 2.5

a) P(X = 0| lambda = 2.5) = e^(-2.5) * (2.5)^0 / 0! = 0.0821
b) P(X >= 1) = 1 - P(X = 0) = 0.9179

In [19]:
#python code 

rate =2.5


In [20]:
n=np.arange(0,10)

In [24]:
poisson_a=stats.poisson.pmf(n,rate)
poisson_a

array([0.082085  , 0.2052125 , 0.25651562, 0.21376302, 0.13360189,
       0.06680094, 0.02783373, 0.00994062, 0.00310644, 0.0008629 ])

In [25]:
poisson_a[0]

0.0820849986238988

In [26]:
#at least one work- related injury occurs

poisson_b=1-poisson_a[0]
poisson_b

0.9179150013761012

# 4. A 5-litre bucket of water is taken from a swamp. The water contains 75 mosquito larvae. A 200mL flask of water is taken form the bucket for further analysis. What is
a) the expected number of larvae in the flask?

b) the probability that the flask contains at least one mosquito lava?

lambda = 75 per 5L lambda = 3 per 200ml i.e expected number 3
P(X >= 1) = 1 - p(X = 0) * e^ -3 * 3 ^ 0 / 0! = 0.9502

In [28]:
#calculate the rate per 200 ml

rate =(75/5000)*200
rate

3.0

In [29]:

n=np.arange(0,10)

In [31]:
#calculate that there are no mosquitos

poisson=stats.poisson.pmf(n,rate)
poisson

array([0.04978707, 0.14936121, 0.22404181, 0.22404181, 0.16803136,
       0.10081881, 0.05040941, 0.02160403, 0.00810151, 0.0027005 ])

In [33]:
poisson[0]

0.049787068367863944

In [35]:
prob_b=1-poisson[0]
prob_b

0.950212931632136

# 5. Given Standardized normal distribution (mean = 0 and SD = 1), what is the probability that
a) Z is less than -1.57 or greater than 1.84?

b) What is the value of Z if only 2.5% of all possible Z values are larger?

b)0.0911
c)+1.96

In [36]:
#calculate the probabilty that the z is between -1.57 to 1.84

stats.norm.cdf(1.84) - stats.norm.cdf(-1.57)

0.9089083257022832

In [37]:
#Probability that the z is less than -1.57 or greater than 1.84

prob_a=1-0.9089083257022832
prob_a

0.09109167429771681

# 6. Why the need of Standardization? Why do we us Z instead of “the Number of Standard Deviations”? 

In [0]:
Normally Distributed random variable take on many different units of measure: rupees, cms, inches, Kg, minutes. 
By standardizing, you remove the units as such we do not require separate Normal Distribution table for each variable 
and one Standardized Distribution Table can be used for any random variable


# 7. A radar unit is used to measure speeds of cars on a Mumbai – Pune Highway. The speeds are normally distributed with a mean of 70 km/hr and a standard deviation of 10 km/hr.

a)What is the probability that a car picked at random is travelling at more than 100 km/hr? 

b)What is the probability that the car speed is between 80 Km / hr and 100 Km / hr

Hint: You can make use of Excel or R

In [0]:
a) Z = (100 – 70) / 10 = 3 
Using Excel function 
Norm.Dist(100, 70, 10, 1) = 0.99865 
Norm.S.Dist(3,1) = 0.99865 
Probability of a random car picked speeding at 100 Km / Hr or more will be  = 1 – 0.99865 = 0.00135

b)Z = (100 – 70) / 10 = 3 Z = (80 – 70) / 10 = 1 
Using Excel function 
Norm.Dist(100, 70, 10, 1) = 0.998650 
Norm.Dist(80, 70, 10, 1) = 0.841345
Probability of a random car picked having a speed between 80 Km / Hr and 100 Km / Hr = 0.998650 – 0.841345 = 0.157305 
This means that 15.73% of the cars are traveling between 80 Km / Hr and 100 Km / Hr


# 8. Given a normal distribution with mu = 50 and sigma = 4, what is the probability that

a) X > 43?

b) Five percent of the values are less than what X value?

In [0]:
a)0.9599
b)43.42